### ISSUE TITLE
Cannot scale up with `add_overlay`

### ISSUE THREAD

**Issue by bordaigorl** [pikepdf/pikepdf#275] opened 2021-11-27 22:31 UTC
I am trying to use `add_overlay` to place a page into a bigger one and I want to scale up the page I am copying.
My code looks like this

```python
from pikepdf import Pdf, Page, Rectangle

from pikepdf import Pdf, Page, Rectangle

pdf = Pdf.open("input1.pdf")

x, y, w, h = pdf.pages[0].trimbox
w, h = w-x, h-x

pdf.add_blank_page(page_size=(2*w,2*h))
pdf.pages[-1].add_overlay(pdf.pages[5], Rectangle(0,0,w*1.5,h*1.5))
pdf.save("output.pdf")
```

but the result is that I get page 5 copied in the last page with the same size in the original but centered in the given rectangle.
If I use

    pdf.pages[-1].add_overlay(pdf.pages[5], Rectangle(0,0,w/2,h/2))

the page gets scaled by half, which is what I'd expect.

Is there a fundamental limitation in scaling up, or is it just a bug?

**Comment by dreua** [comment] 2021-11-28 09:28
Duplicate of #276 . @bordaigorl you should be able to close your own issues and edit their titles (edit button at the top right).

**Comment by jbarlow83** [comment] 2021-11-28 09:51
@dreua GitHub had some outages today, don't be surprised to see some duplicate issues.

**Closed** 2021-11-28 09:51 UTC

**Comment by bordaigorl** [comment] 2021-11-28 19:57
Yes sorry I submitted the issue and got an error from GitHub so I assumed the submission failed, then retried.
