### ISSUE TITLE
segmentation fault on appending pages

### ISSUE THREAD

**Issue by abrarahmedbcg** [pikepdf/pikepdf#66] opened 2019-11-21 00:04 UTC
We are getting segmentation fault while reading single page pdf files and creating a new page.
Below is the sample code. it assumes file is already open in binary file stream.

> pikepdf                  1.7.0 

```
def GetPagesAndText(self):
        with pikepdf.Pdf.open(self.pdf_file_stream) as pdf:
            for n, page in enumerate(pdf.pages):
                with pikepdf.Pdf.new() as single_page:
                    single_page.pages.append(page)
                    f = io.BytesIO()
                    dst.save(f, linearize=True)
                    self.child_pdf_streams.append(f)
        return self.child_pdf_streams
```

pdf file for testing , [23383.pdf](https://github.com/pikepdf/pikepdf/files/3872111/23383.pdf)

the segmentation fault happens on line, 
` single_page.pages.append(page)`

**Comment by jbarlow83** [comment] 2019-11-21 11:59
Here's a workaround that at least does not crash
```python

single_page.pages.append(copy.copy(page))
```

----

This might be qpdf bug, or a pikepdf memory bug. It is specific to some oddity of 23383.pdf which has syntax errors per Acrobat but none according to qpdf. Typical stack trace:

```
0   libqpdf.26.dylib              	0x000000010fea55ed QPDF::resolve(int, int) + 63
1   libqpdf.26.dylib              	0x000000010feb99de QPDFObjectHandle::dereference() + 56
2   libqpdf.26.dylib              	0x000000010feb9bc2 QPDFObjectHandle::isNull() + 14
3   libqpdf.26.dylib              	0x000000010fee3ea1 QPDF_Dictionary::hasKey(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 49
4   libqpdf.26.dylib              	0x000000010fee403b QPDF_Dictionary::getKeys() + 73
5   libqpdf.26.dylib              	0x000000010febbed4 QPDFObjectHandle::getKeys() + 176
6   libqpdf.26.dylib              	0x000000010fea7b30 QPDF::reserveObjects(QPDFObjectHandle, QPDF::ObjCopier&, bool) + 614
7   libqpdf.26.dylib              	0x000000010fea7bf3 QPDF::reserveObjects(QPDFObjectHandle, QPDF::ObjCopier&, bool) + 809
8   libqpdf.26.dylib              	0x000000010fea7b60 QPDF::reserveObjects(QPDFObjectHandle, QPDF::ObjCopier&, bool) + 662
9   libqpdf.26.dylib              	0x000000010fea7b60 QPDF::reserveObjects(QPDFObjectHandle, QPDF::ObjCopier&, bool) + 662
10  libqpdf.26.dylib              	0x000000010fea7b60 QPDF::reserveObjects(QPDFObjectHandle, QPDF::ObjCopier&, bool) + 662
11  libqpdf.26.dylib              	0x000000010fea75c5 QPDF::copyForeignObject(QPDFObjectHandle) + 133
12  libqpdf.26.dylib              	0x000000010ff04f05 QPDF::insertPage(QPDFObjectHandle, int) + 127
13  libqpdf.26.dylib              	0x000000010ff05ade QPDF::addPage(QPDFObjectHandle, bool) + 162
14  _qpdf.cpython-37m-darwin.so   	0x000000010fd5391a PageList::insert_page(unsigned long, QPDFObjectHandle) + 442 (PointerHolder.hh:171)
15  _qpdf.cpython-37m-darwin.so   	0x000000010fd52384 PageList::insert_page(unsigned long, pybind11::handle) + 244 (PointerHolder.hh:171)
```

The crash site is https://github.com/qpdf/qpdf/blob/9b0c6022d7aa60ca7823a9e5292884ecaf121963/libqpdf/QPDF.cc#L1992

Under the circumstances it appears that one of {this, m, resolving} is corrupt by this point and the error is while setting up the function call. Looks like we'll need to find a way to valgrind it.

```asm
    0x103cb59d2 <+46>:   callq  0x103ccaa12               ; QPDFObjGen::QPDFObjGen(int, int)
    0x103cb59d7 <+51>:   movq   (%r13), %rax
    0x103cb59db <+55>:   movl   $0xb8, %ebx
->  0x103cb59e0 <+60>:   movq   (%rax), %rdi
    0x103cb59e3 <+63>:   addq   %rbx, %rdi
    0x103cb59e6 <+66>:   movq   %r14, %rsi
    0x103cb59e9 <+69>:   callq  0x103cc0520               ; unsigned long std::__1::__tree<QPDFObjGen, std::__1::less<QPDFObjGen>, std::__1::allocator<QPDFObjGen> >::__count_unique<QPDFObjGen>(QPDFObjGen const&) const
    0x103cb59ee <+74>:   testq  %rax, %rax
```

**Comment by abrarahmedbcg** [comment] 2019-11-21 19:21
@jbarlow83  , this work around does not crash the code, but now the pdf pages are empty, so the shallow copy is properly copying the pdfobject, and with deepcopy get this error

>  cannot pickle 'pikepdf._qpdf.Object' object

**Comment by jbarlow83** [comment] 2019-11-26 00:06
Do you have other files that reproduce this issue or just that one?

I tried your code on the PDF 1.7 reference manual (755 pages, demonstrates a lot of PDF features) and some other files in my test suite and it seems to work fine.

**Comment by abrarahmedbcg** [comment] 2019-11-26 20:37
Here is a zipfile that contains 2 additional files, that cause this issue

[seg-fault-examples.zip](https://github.com/pikepdf/pikepdf/files/3893934/seg-fault-examples.zip)

**Comment by RAbraham** [comment] 2020-06-09 20:11
We are getting a similar error. I'm afraid we can't share the document as it is a personally identifying document. On inspection, they are scanned pages.

**Comment by jbarlow83** [comment] 2020-07-04 09:21
As mentioned in the linked issue this is a probably a QPDF issue and we'll have to wait for a fix there.

**Comment by jbarlow83** [comment] 2020-12-01 01:23
I believe this issue is now resolved as of pikepdf v2.x, provided pikepdf is linked against QPDF 10.0.3 or newer.

**Closed by jbarlow83** 2020-12-01 01:23 UTC
