### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by josch** [pikepdf/pikepdf#329] opened 2022-04-13 18:14 UTC
Hi,

consider the following code:

```py
import pikepdf

for i in range(100000):
	with pikepdf.new() as pdf:
		pdf.add_blank_page()
```

running this creates a process that increases in the RAM usage up to 805 MB. Increasing the number of iterations increases the memory usage of the process. Decreasing the number of iterations uses less RAM overall.

So I suspect there is either a memory leak somewhere or I am using pikepdf wrongly? This is a problem when using pikepdf in long running process like as part of a web application.

Thanks!

**Comment by jbarlow83** [comment] 2022-04-13 21:39
Using `gc.collect()`, it appears that the memory never leaked. CPython didn't just run a garbage collection cycle. I suspect if you add gc.collect() to your loop you'll see lower RAM usage.

```
def test_leak():
    before = gc.get_count()
    for _ in range(100):
        with pikepdf.new() as pdf:
            pdf.add_blank_page()
    gc.collect()
    after = gc.get_count()

    for n in range(3):
        assert after[n] <= before[n]
```

There are many tests that run gc.collect() and confirm reference counts after e.g. transferring a page from one PDF to another; see test_refcount.py.

**Comment by mara004** [comment] 2022-04-13 21:45
@jbarlow83 I can't reproduce that `gc.collect()` would make any difference in this case. The problem of steadily increasing memory usage still persists, and memory load will only go down once the process is terminated.

**Comment by jbarlow83** [comment] 2022-04-13 23:24
QPDF is converting from its homebrewed PointerHolder to standard shared_ptr for its version 11. pikepdf will switch to shared_ptr as well drop its PointerHolder usage entirely and do a major release to mark the occasion.

From my perspective there's no point in looking any further until that transition takes place. The versions of pikepdf, qpdf and pybind11 will all be factors.

**Closed** 2022-07-13 08:44 UTC
Labels: waiting for qpdf

**Comment by mara004** [comment] 2022-07-13 19:19
Thanks, that looks plausible. I'll test once the next release is published.

**Comment by mara004** [comment] 2022-07-17 10:31
I can confirm the fix. Memory load remains constant now.
