### ISSUE TITLE
PyPi Metadata and Filename version mismatch

### ISSUE THREAD

**Issue by nielsbox** [pikepdf/pikepdf#360] opened 2022-06-23 14:21 UTC
```
#0 14.69   WARNING: Requested pikepdf==5.1.5 from https://files.pythonhosted.org/packages/6a/4b/5f456ff997f66e4ec6eb53b32c3db2b9fd03889e9768619cc3d6e5ed767f/pikepdf-5.1.5.tar.gz#sha256=0af747f989d0de8302e6e58e3da4c38d230bad6138b1cbb8dc6838e16285e63f (from -r requirements.txt (line 26)), but installing version 0.0
#0 14.70 Discarding https://files.pythonhosted.org/packages/6a/4b/5f456ff997f66e4ec6eb53b32c3db2b9fd03889e9768619cc3d6e5ed767f/pikepdf-5.1.5.tar.gz#sha256=0af747f989d0de8302e6e58e3da4c38d230bad6138b1cbb8dc6838e16285e63f (from https://pypi.org/simple/pikepdf/) (requires-python:>=3.7): Requested pikepdf==5.1.5 from https://files.pythonhosted.org/packages/6a/4b/5f456ff997f66e4ec6eb53b32c3db2b9fd03889e9768619cc3d6e5ed767f/pikepdf-5.1.5.tar.gz#sha256=0af747f989d0de8302e6e58e3da4c38d230bad6138b1cbb8dc6838e16285e63f (from -r requirements.txt (line 26)) has inconsistent version: filename has '5.1.5', but metadata has '0.0'
#0 14.70 ERROR: Could not find a version that satisfies the requirement pikepdf==5.1.5 (from versions: 0.1rc1, 0.1rc3, 0.1rc4, 0.1rc5, 0.1.0.post1, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.1.10rc1, 0.1.10, 0.2.0, 0.2.1, 0.2.2, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.7.post1, 0.3.7.post2, 0.9.0, 0.9.1, 0.9.2, 0.10.0, 0.10.1, 0.10.2, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.2.0, 1.3.0, 1.3.1, 1.4.0, 1.5.0.post0, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.7.0, 1.7.1, 1.8.0, 1.8.1, 1.8.2, 1.8.3, 1.9.0, 1.10.0, 1.10.1, 1.10.2, 1.10.3, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.12.0, 1.13.0, 1.14.0, 1.15.0, 1.15.1, 1.16.0, 1.16.1, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.18.0, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 2.0.0b1, 2.0.0b2, 2.0.0, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.3.0, 2.4.0, 2.5.0, 2.5.1, 2.5.2, 2.6.0, 2.7.0, 2.8.0, 2.8.0.post1, 2.8.0.post2, 2.9.0, 2.9.1, 2.9.2, 2.10.0, 2.11.0, 2.11.1, 2.11.2, 2.11.3, 2.11.4, 2.12.0, 2.12.1, 2.12.2, 2.13.0, 2.14.0, 2.14.1, 2.14.2, 2.15.0, 2.15.1, 2.16.0, 2.16.1, 3.0.0b1, 3.0.0b2, 3.0.0b3, 3.0.0, 3.1.0, 3.1.1, 3.2.0, 4.0.0, 4.0.1, 4.0.1.post1, 4.0.2, 4.1.0, 4.2.0, 4.3.0, 4.3.1, 4.4.0, 4.4.1, 4.5.0, 5.0.0, 5.0.1, 5.1.0, 5.1.1, 5.1.2, 5.1.3, 5.1.4, 5.1.4.post1, 5.1.5)
#0 14.70 ERROR: No matching distribution found for pikepdf==5.1.5
```

**Comment by mara004** [comment] 2022-06-23 14:41
Looks like a duplicate of https://github.com/pikepdf/pikepdf/issues/359

**Closed** 2022-06-23 20:39 UTC
