### ISSUE TITLE
pikepdf._qpdf.PdfError on a specific PDF file with pikepdf >= 4.5.0

### ISSUE THREAD

**Issue by lsamper** [pikepdf/pikepdf#317] opened 2022-03-16 09:17 UTC
Hi,
I have a bug with a specific PDF (which I can't publish unfortunately). 

The error is the following:
```
Traceback (most recent call last):
  File "/tests/test_pikepdf.py", line 10, in test_pikepdf
    pdf.save("/tmp/toto.pdf")
  File "/usr/local/lib/python3.8/site-packages/pikepdf/_methods.py", line 774, in save
    self._save(
pikepdf._qpdf.PdfError: operation for dictionary attempted on object of type null: returning null for attempted key retrieval
```

It happens with this python code, on the save statement:

```
import pikepdf
from pathlib import Path
fpath = Path("tests/fixtures/scanned_rotation.pdf")
pdf = pikepdf.Pdf.open(fpath)
pdf.save("/tmp/toto.pdf")
```

This is my Dockerfile to reproduce the problem:

```
FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8
RUN apt-get update -q -y && apt-get upgrade -q -y
RUN python -m pip install --upgrade pip
RUN pip install --no-cache-dir install pikepdf
COPY app /app
COPY tests /tests
WORKDIR /app
```

It worked until pikepdf version 4.4.1 but from 4.5.0 to current version (5.0.1) it raises this `pikepdf._qpdf.PdfError` exception.

Thank you for your help and support

**Comment by lsamper** [comment] 2022-03-16 12:06
I did a bit of data analysis to see how often this problem happens.

**On the 66000 pdfs I have, it occurs on about 2000 documents**

All those 2000 PDF that fails with pikepdf 5.0.1 can be processed by an older version of pikepdf. Thus I was able to check some metas:

- Number of files per pdf.pdf_version: 
   - '1.5': 2241
   - '1.6': 2
   - '1.7': 3
- Number of files per pdf.docinfo.get('/Creator') : 
  - "ABBYY FineReader Engine 12": 1416
  -  "pdftk 2.02 - www.pdftk.com": 827
  -  None: 2
  -  "PDFium": 1

If I convert a failing PDF with gs, then I can process it with pikepdf:

`gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.5 -o output.pdf input.pdf`

We data could I give you to help you understand this bug better (and fix it!) ?

**Comment by lsamper** [comment] 2022-03-17 08:35
**Please find attached a PDF that reproduces the bug.**

[empty_pdf_bug.pdf](https://github.com/pikepdf/pikepdf/files/8282996/empty_pdf_bug.pdf)

I was able to remove the content from the PDF to create a PDF file that's reproduces the bug but doesn't contain our customer data.

With pikepdf 2.11, I did:
```
pdf = pdf = pikepdf.Pdf.open("bug_pdf.pdf")
del pdf.Root.Pages.Kids[0].Contents
pdf.save("empty_pdf_bug.pdf")
```

Then when I open it with pikepdf 5.0.1, I get

```

>>> pdf = pikepdf.Pdf.open("empty_pdf_bug.pdf")
>>> pdf.save("/tmp/toto.pdf")

PdfError                                  Traceback (most recent call last)
Input In [46], in <cell line: 2>()
      1 pdf = pikepdf.Pdf.open("empty_pdf_bug.pdf")
----> 2 pdf.save("/tmp/toto.pdf")


    765 if not filename_or_stream:
    766     raise ValueError(
    767         "Cannot save to original filename because the original file was "
    768         "not opening using Pdf.open(..., allow_overwriting_input=True). "
   (...)
    772         "no original filename to save to."
    773     )
--> 774 self._save(
    775     filename_or_stream,
    776     static_id=static_id,
    777     preserve_pdfa=preserve_pdfa,
    778     min_version=min_version,
    779     force_version=force_version,
    780     fix_metadata_version=fix_metadata_version,
    781     compress_streams=compress_streams,
    782     stream_decode_level=stream_decode_level,
    783     object_stream_mode=object_stream_mode,
    784     normalize_content=normalize_content,
    785     linearize=linearize,
    786     qdf=qdf,
    787     progress=progress,
    788     encryption=encryption,
    789     samefile_check=getattr(self, '_tmp_stream', None) is None,
    790     recompress_flate=recompress_flate,
    791 )

PdfError: operation for dictionary attempted on object of type null: returning null for attempted key retrieval

```

**Comment by jbarlow83** [comment] 2022-03-17 08:53
I won't be able to look at this till April. Too busy with other projects at $dayjob.

**Comment by lsamper** [comment] 2022-03-17 09:05
Hi, 
Thanks for your reply. Sure, I understand.

The PDF works with qpdf and the generated file `out.pdf` behaves similarity with pikepdf.

```
$ qpdf empty_pdf_bug.pdf out.pdf
$ qpdf --version
qpdf version 9.1.1
Run qpdf --copyright to see copyright and license information.
```

**Comment by stumpylog** [comment] 2022-05-03 00:07
I can compile this is still an issue with 5.1.1.  However, a newer qpdf returns something maybe useful:
```
>> qpdf --version
qpdf version 10.6.3
>> qpdf empty_pdf_bug.pdf out.pdf
WARNING: empty_pdf_bug.pdf: can't find PDF header
WARNING: empty_pdf_bug.pdf: file is damaged
WARNING: empty_pdf_bug.pdf: can't find startxref
WARNING: empty_pdf_bug.pdf: Attempting to reconstruct cross-reference table
qpdf: empty_pdf_bug.pdf: unable to find trailer dictionary while recovering damaged file
```

So the file is damaged, but previously could be read/written by pikepdf and qpdf?

**Comment by jbarlow83** [comment] 2022-05-03 00:25
@stumpylog I don't understand your comment. Is it an issue in 5.1.1 or is the issue that curl truncated the file?

**Comment by stumpylog** [comment] 2022-05-03 00:56
It is still an issue with 5.1.1.  And qpdf 10.6.3 reads and writes using the file above no problem.

I had thought a newer qpdf was giving some information that might be helpful, but that was operator error.

**Comment by furchtlos76** [comment] 2022-05-03 06:28
If you need any more testfiles, let me know, at my place the files not working are all with an ocr layer done with finereader as i can see in the file details. Thanks alot for looking in this bug.

**Comment by sondrelg** [comment] 2022-05-03 12:16
This might not be of much help, but the change in question should be contained here: https://github.com/pikepdf/pikepdf/compare/377891f..e3ac85a. There isn't too many changes to go through.

I was hoping to install from specific commits until finding the PR responsible, but building with `pip install git+https://github.com/pikepdf/pikepdf.git@377891f0ebaf86c6ba221c2b25e3e07dc9fe1296` fails. Any tips on how to make it pass? 

It fails with:
```
src/qpdf/pikepdf.h:15:10: fatal error: 'qpdf/PointerHolder.hh' file not found
```

Is `PointerHolder.hh` not checked into source control?

**Comment by mara004** [comment] 2022-05-03 13:12
@sondrelg You need to install qpdf and its headers to be able to build pikepdf from source. pikepdf does not attempt to download/build qpdf on its own. See [the documentation](https://pikepdf.readthedocs.io/en/latest/installation.html#building-from-source).

**Comment by mara004** [comment] 2022-05-03 13:28
I can't find anything suspicious in the referenced diff. I guess this might more likely be a pikepdf - qpdf integration issue (i. e. some behaviour changed in qpdf so that an assumption in [`pikepdf/src/qpdf/qpdf.cpp:_save()`](https://github.com/pikepdf/pikepdf/blob/ddac180f715ecbf6face83af944e50ed9f13cfda/src/qpdf/qpdf.cpp#L658) no longer holds true).

**Comment by mara004** [comment] 2022-05-03 14:01
> You could try qpdf in.pdf out.pdf with your test file. If that produces a similar error, the problem and solution may lie in the qpdf project. There's a high probability this is the case imo.

> The PDF works with qpdf and the generated file out.pdf behaves similarity with pikepdf.

Re-reading this, I presume there's a great likelihood the system-provided qpdf and the one shipped with pikepdf's wheel may have been different versions? However, to actually find out on which side the issue is, the system's qpdf and pikepdf's qpdf must be identical...

**Comment by chantzish** [comment] 2022-05-04 01:22
> This might not be of much help, but the change in question should be contained here: https://github.com/pikepdf/pikepdf/compare/377891f..e3ac85a. There isn't too many changes to go through.
> 
> I was hoping to install from specific commits until finding the PR responsible, but building with `pip install git+https://github.com/pikepdf/pikepdf.git@377891f0ebaf86c6ba221c2b25e3e07dc9fe1296` fails. Any tips on how to make it pass?
> 
> It fails with:
> 
> ```
> src/qpdf/pikepdf.h:15:10: fatal error: 'qpdf/PointerHolder.hh' file not found
> ```
> 
> Is `PointerHolder.hh` not checked into source control?

I was able to confirm the responsible commit is https://github.com/pikepdf/pikepdf/commit/63274fc534a356508b232f921af9475a06dad451

**Comment by furchtlos76** [comment] 2022-05-07 12:34
@mara004  i use it with paperless ngx inside a docker. is it possible to install from source with patch inside a docker, never did this, so any help is apprechiated. Thanks

**Comment by mara004** [comment] 2022-05-07 15:08
I never used docker myself, but I suppose you can follow the default sourcebuild procedure as outlined in the docs.
Just apply the patch after checking out the repository, like this:
```bash
wget "https://patch-diff.githubusercontent.com/raw/pikepdf/pikepdf/pull/339.patch"
git apply "./339.patch"
```

**Closed** 2022-05-17 06:08 UTC
