### ISSUE TITLE
[documentation] installation fails if qpdf is not installed.

### ISSUE THREAD

**Issue by davidbstein** [pikepdf/pikepdf#208] opened 2021-06-13 02:51 UTC
Sorry to not do this as a PR. Very minor installation instructions nitpick:

on osx I needed to `brew install qpdf` in order to install `pikepdf` within a virtual environment.

Also wanted to throw a copy/paste of the error message anyone who ran `pipenv install` and then searched for the error:

```
  In file included from src/qpdf/qpdf_pagelist.cpp:9:
  src/qpdf/pikepdf.h:15:10: fatal error: 'qpdf/PointerHolder.hh' file not found
  #include <qpdf/PointerHolder.hh>
           ^~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.
  ----------------------------------------
  ERROR: Failed building wheel for pikepdf
ERROR: Could not build wheels for pikepdf which use PEP 517 and cannot be installed directly
```

**Comment by jbarlow83** [comment] 2021-06-13 05:25
The issue is that we don't have binary wheels on Apple Silicon, due to the inavailability of native ARM CI bots, terrible performance of ARM emulation  on x64 CI bots, and hassle of setting up cross compilers.

I'm waiting for more progress in the CI ecosystem.

**Comment by jbarlow83** [comment] 2021-06-15 08:54
I uploaded a manually created Apple Silicon pikepdf.

**Comment by jbarlow83** [comment] 2021-06-15 08:54
Closing as equivalent to #153

**Closed by jbarlow83** 2021-06-15 08:54 UTC
