### ISSUE TITLE
pikepdf gets stuck when using smart_open

### ISSUE THREAD

**Issue by Kilavagora** [pikepdf/pikepdf#204] opened 2021-05-24 21:32 UTC
pikepdf does not play nicely with smart_open. See: RaRe-Technologies/smart_open#622. 

I could not figure out the root cause, but per https://github.com/RaRe-Technologies/smart_open/issues/622#issuecomment-845566931, the issue might have been caused by pikepdf also, so creating this in here as well.

**Comment by jbarlow83** [comment] 2021-05-25 06:49
I left a comment on that issue because I believe the problem is due to the design of smart_open and would affect any software that does a lot of random IO, not just pikepdf. My recommendation would be to avoid smart_open and use FUSE mounted file systems, or (best performance) download files to BytesIO and then pass them to pikepdf.

I added a note to the documentation that performance may be poor if the Python file stream do not implement buffering.

I'll close this but I am happy to take further steps if it becomes apparent we do need to adjust pikepdf in some way.

**Closed by jbarlow83** 2021-05-25 06:49 UTC
Labels: third party issue
