### ISSUE TITLE
Unable to view pdf with pdf or pdf.pages in jupyter notebook

### ISSUE THREAD

**Issue by sarahberner** [pikepdf/pikepdf#52] opened 2019-07-15 22:00 UTC
First, I'm really excited to use this, thank you for your work on it!

I am simply following the first page of the tutorial, and would like to be able to see the pdf. My output is not an image of the pdf, but instead a dead link that says "View PDF". Clicking on this either does nothing (in IE), or opens a new empty tab called untitled with an impossibly long string in the URL (in Chrome).

Even a one page pdf will do this. This happens whether I type 'pdf' to see the whole thing, or pdf.pages[0] to see the first page (or any page).

Any advice for this? Thank you!

**Comment by jbarlow83** [comment] 2019-07-15 23:18
I'm not entirely sure because this functionality depends on your browser and Jupyter as well. If you have a browser extension or third party PDF viewer this could interfere.

You are supposed to see "View PDF" in some cases, but that should take you to a real PDF.

Can you check the versions for Jupyter and IE? 

What operating system?

**Comment by sarahberner** [comment] 2019-07-15 23:36
I'm using Python, version 3.7.3, Windows 7, jupyter version 4.4.0, IE version 11.0.9600.19399.
I don't have a third party PDF viewer nor I believe any browser extensions.

**Comment by jbarlow83** [comment] 2019-07-16 23:36
I have a feeling it won't work in that version of IE at all but should work in a recent Chrome or Firefox.

Try running this in a Jupyter notebook. It should also display the "View PDF" link, and that should lead to a blank PDF. It's completely independent of pikepdf; if this causes issues, then the problem is with Jupyter.

```python
class EmptyPdf:
    EMPTY_PDF = (
        b"%PDF-1.3\n"
        b"1 0 obj\n"
        b"<< /Type /Catalog /Pages 2 0 R >>\n"
        b"endobj\n"
        b"2 0 obj\n"
        b"<< /Type /Pages /Kids [] /Count 0 >>\n"
        b"endobj\n"
        b"xref\n"
        b"0 3\n"
        b"0000000000 65535 f \n"
        b"0000000009 00000 n \n"
        b"0000000058 00000 n \n"
        b"trailer << /Size 3 /Root 1 0 R >>\n"
        b"startxref\n"
        b"110\n"
        b"%%EOF\n"
    )
    
    def _repr_mimebundle_(self, include, exclude):
        return {'application/pdf': self.EMPTY_PDF}
EmptyPdf()
```

This is how it should look when loaded in Firefox:

<img width="907" alt="Screen Shot 2019-07-16 at 16 35 03" src="https://user-images.githubusercontent.com/1825843/61336827-b3f56a80-a7e7-11e9-8955-fd794ad7f306.png">

**Comment by jbarlow83** [comment] 2019-08-13 06:12
I'll close the issue now. If you have further related questions feel free to reopen it.

**Closed by jbarlow83** 2019-08-13 06:12 UTC

**Comment by NTR0314** [comment] 2021-12-17 12:10
Hello,

I have a similar issue: namely on Firefox viewing pdf pages works, but on Chrome it does not. Does anyone know if I have to change specific settings in Google Chrome (Version 96.0.4664.45 (Official Build) (64-bit)) to make it work in Chrome? 

In Google Chrome the link appears just a like in the Screenshot of jbarlow83: "data:application/pdf;base64,JVBERi0xLj...." but Chrome does not display the pdf and interprets it as an url.

**Comment by jbarlow83** [comment] 2021-12-20 01:00
Inside VSCode, the notebook renderer does not support PDF so it does not work.

Latest Firefox and Chromium work for me using pikepdf 4.2. I rarely use Chromium so I assume all my settings are default.

Quite possible if you have PDFs set to a custom viewer or to download, that they will behave differently.

My example above was not very good. It's a valid PDF with no pages, hence the "0 of 0". If this is what you see, the PDF viewer is probably working.  It's understandable that some PDF viewers may not like that - try opening a small known good PDF. A data URL is acceptable in this situation and browsers usually know what to do with them.
