### ISSUE TITLE
v8 pip build issues

### ISSUE THREAD

**Issue by tomtechnologies** [pikepdf/pikepdf#489] opened 2023-07-14 01:02 UTC
With the v8 release overnight I've seen one of my environments pipeline break. Given the QPDF version change I suspect that this version support in the lts-alpine package repository, but leaving this here for anyone else that has issue.

Environment is a docker container

Image: node:lts-apline

`src/core/job.cpp:117:65: error: 'class QDFJob' has no member named 'createQPDF'`

![image](https://github.com/pikepdf/pikepdf/assets/18191078/058e5039-847f-43f4-9476-d8a60df7d98a)

I am able to work around by version pinning with `pip3 install pikepdf==7.2`

Dockerfile contents is similar to (layers simplified);

```
FROM node:lts-alpine
RUN apk add --no-cache libc6-compat
RUN apk update
RUN  apk add nmap &&\
        apk add gcc &&\
        apk add g++ &&\
        apk add qpdf-dev &&\
        apk add python3 &&\
        apk add python3-dev &&\
        apk add py3-pip &&\
        apk update && \
        apk add --no-cache

RUN pip3 install --upgrade pip
RUN pip3 install pikepdf
```

**Comment by jbarlow83** [comment] 2023-07-14 20:31
The issue is that QPDF 11.5.0 is now required in any downstream. I am going to close this because this was expected and there's nothing I can do until downstreams update their versions.

**Closed by jbarlow83** 2023-07-14 20:31 UTC
